from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_CheatingDetection(object):
    def setupUi(self, CheatingDetection):
        CheatingDetection.setObjectName("CheatingDetection")
        CheatingDetection.setWindowModality(QtCore.Qt.WindowModal)
        CheatingDetection.resize(1440, 960)
        CheatingDetection.setWindowTitle("")
        CheatingDetection.setStyleSheet("font: 12pt \"华文中宋\";\n""")
        self.gridLayout = QtWidgets.QGridLayout(CheatingDetection)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_4 = QtWidgets.QFrame(CheatingDetection)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(CheatingDetection)
        self.label_13.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font: 12pt \"华文行楷\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.show_box_ckb = QtWidgets.QCheckBox(CheatingDetection)
        self.show_box_ckb.setStyleSheet("font: 12pt \"华文中宋\";")
        self.show_box_ckb.setChecked(True)
        self.show_box_ckb.setObjectName("show_box_ckb")
        self.horizontalLayout_10.addWidget(self.show_box_ckb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.close_source_btn = QtWidgets.QPushButton(CheatingDetection)
        self.close_source_btn.setStyleSheet("font: 12pt \"华文中宋\";")
        self.close_source_btn.setObjectName("close_source_btn")
        self.horizontalLayout_10.addWidget(self.close_source_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.video_screen = QtWidgets.QLabel(CheatingDetection)
        self.video_screen.setMinimumSize(QtCore.QSize(840, 630))
        self.video_screen.setAutoFillBackground(False)
        self.video_screen.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.video_screen.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_screen.setText("")
        self.video_screen.setObjectName("video_screen")
        self.verticalLayout_4.addWidget(self.video_screen)
        self.video_process_bar = QtWidgets.QSlider(CheatingDetection)
        self.video_process_bar.setAutoFillBackground(False)
        self.video_process_bar.setMinimum(-1)
        self.video_process_bar.setMaximum(-1)
        self.video_process_bar.setProperty("value", -1)
        self.video_process_bar.setOrientation(QtCore.Qt.Horizontal)
        self.video_process_bar.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.video_process_bar.setTickInterval(0)
        self.video_process_bar.setObjectName("video_process_bar")
        self.verticalLayout_4.addWidget(self.video_process_bar)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.time_process_label = QtWidgets.QLabel(CheatingDetection)
        self.time_process_label.setStyleSheet("font: 12pt \"华文中宋\";")
        self.time_process_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_process_label.setObjectName("time_process_label")
        self.horizontalLayout_11.addWidget(self.time_process_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.play_video_btn = QtWidgets.QPushButton(CheatingDetection)
        self.play_video_btn.setStyleSheet("font: 12pt \"华文中宋\";")
        self.play_video_btn.setObjectName("play_video_btn")
        self.horizontalLayout_11.addWidget(self.play_video_btn)
        self.stop_playing_btn = QtWidgets.QPushButton(CheatingDetection)
        self.stop_playing_btn.setStyleSheet("font: 12pt \"华文中宋\";")
        self.stop_playing_btn.setObjectName("stop_playing_btn")
        self.horizontalLayout_11.addWidget(self.stop_playing_btn)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(2, 1)
        self.horizontalLayout_11.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_9 = QtWidgets.QFrame(CheatingDetection)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout.addWidget(self.line_9)
        self.label_11 = QtWidgets.QLabel(CheatingDetection)
        self.label_11.setStyleSheet("font: 12pt \"华文行楷\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.video_resource_list = QtWidgets.QListWidget(CheatingDetection)
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.video_resource_list.setFont(font)
        self.video_resource_list.setStyleSheet("font: 12pt \"华文隶书\";")
        self.video_resource_list.setAlternatingRowColors(False)
        self.video_resource_list.setObjectName("video_resource_list")
        self.horizontalLayout.addWidget(self.video_resource_list)
        self.line_7 = QtWidgets.QFrame(CheatingDetection)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout.addWidget(self.line_7)
        self.label_12 = QtWidgets.QLabel(CheatingDetection)
        self.label_12.setStyleSheet("font: 12pt \"华文行楷\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.video_resource_file_list = QtWidgets.QListWidget(CheatingDetection)
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.video_resource_file_list.setFont(font)
        self.video_resource_file_list.setStyleSheet("font: 12pt \"华文隶书\";")
        self.video_resource_file_list.setObjectName("video_resource_file_list")
        self.horizontalLayout.addWidget(self.video_resource_file_list)
        self.line_12 = QtWidgets.QFrame(CheatingDetection)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout.addWidget(self.line_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_4 = QtWidgets.QLabel(CheatingDetection)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 12pt \"华文行楷\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.label_15 = QtWidgets.QLabel(CheatingDetection)
        self.label_15.setStyleSheet("font: 12pt \"华文中宋\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.cheating_list_spin = QtWidgets.QSpinBox(CheatingDetection)
        self.cheating_list_spin.setStyleSheet("color:rgb(255,255,255);")
        self.cheating_list_spin.setMinimum(1)
        self.cheating_list_spin.setMaximum(100)
        self.cheating_list_spin.setProperty("value", 20)
        self.cheating_list_spin.setObjectName("cheating_list_spin")
        self.horizontalLayout_14.addWidget(self.cheating_list_spin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.cheating_list = QtWidgets.QListWidget(CheatingDetection)
        self.cheating_list.setMinimumSize(QtCore.QSize(0, 0))
        self.cheating_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cheating_list.setFont(font)
        self.cheating_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cheating_list.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cheating_list.setStyleSheet("font: 10pt \"华文琥珀\";")
        self.cheating_list.setLineWidth(1)
        self.cheating_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cheating_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cheating_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.cheating_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.cheating_list.setTextElideMode(QtCore.Qt.ElideLeft)
        self.cheating_list.setMovement(QtWidgets.QListView.Static)
        self.cheating_list.setProperty("isWrapping", False)
        self.cheating_list.setResizeMode(QtWidgets.QListView.Fixed)
        self.cheating_list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.cheating_list.setViewMode(QtWidgets.QListView.ListMode)
        self.cheating_list.setModelColumn(0)
        self.cheating_list.setSelectionRectVisible(False)
        self.cheating_list.setObjectName("cheating_list")
        self.verticalLayout_2.addWidget(self.cheating_list)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(CheatingDetection)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.real_time_catch_lbl = QtWidgets.QLabel(CheatingDetection)
        self.real_time_catch_lbl.setEnabled(True)
        self.real_time_catch_lbl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.real_time_catch_lbl.setStyleSheet("font: 12pt \"华文行楷\";")
        self.real_time_catch_lbl.setObjectName("real_time_catch_lbl")
        self.horizontalLayout_2.addWidget(self.real_time_catch_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_14 = QtWidgets.QLabel(CheatingDetection)
        self.label_14.setStyleSheet("font: 12pt \"华文中宋\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.real_time_catch_spin = QtWidgets.QSpinBox(CheatingDetection)
        self.real_time_catch_spin.setStyleSheet("color:rgb(255,255,225);")
        self.real_time_catch_spin.setMinimum(1)
        self.real_time_catch_spin.setMaximum(50)
        self.real_time_catch_spin.setProperty("value", 5)
        self.real_time_catch_spin.setObjectName("real_time_catch_spin")
        self.horizontalLayout_2.addWidget(self.real_time_catch_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.real_time_catch_list = QtWidgets.QListWidget(CheatingDetection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.real_time_catch_list.sizePolicy().hasHeightForWidth())
        self.real_time_catch_list.setSizePolicy(sizePolicy)
        self.real_time_catch_list.setMinimumSize(QtCore.QSize(0, 291))
        self.real_time_catch_list.setSizeIncrement(QtCore.QSize(0, 0))
        self.real_time_catch_list.setBaseSize(QtCore.QSize(0, 0))
        self.real_time_catch_list.setStyleSheet("font: 12pt \"华文琥珀\";")
        self.real_time_catch_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.real_time_catch_list.setFlow(QtWidgets.QListView.LeftToRight)
        self.real_time_catch_list.setObjectName("real_time_catch_list")
        self.verticalLayout.addWidget(self.real_time_catch_list)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)

        self.retranslateUi(CheatingDetection)
        QtCore.QMetaObject.connectSlotsByName(CheatingDetection)
    def retranslateUi(self, CheatingDetection):
        _translate = QtCore.QCoreApplication.translate
        self.label_13.setText(_translate("CheatingDetection", "作弊检测"))
        self.show_box_ckb.setText(_translate("CheatingDetection", "显示边框"))
        self.close_source_btn.setText(_translate("CheatingDetection", "结束"))
        self.time_process_label.setText(_translate("CheatingDetection", "00:00:00/00:00:00"))
        self.play_video_btn.setText(_translate("CheatingDetection", "播放"))
        self.stop_playing_btn.setText(_translate("CheatingDetection", "暂停"))
        self.label_11.setText(_translate("CheatingDetection", "视频通道"))
        self.label_12.setText(_translate("CheatingDetection", "本地视频"))
        self.label_4.setText(_translate("CheatingDetection", "作弊列表"))
        self.label_15.setText(_translate("CheatingDetection", "上限"))
        self.real_time_catch_lbl.setText(_translate("CheatingDetection", "作弊抓拍"))
        self.label_14.setText(_translate("CheatingDetection", "上限"))
