from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_CheatingListItem(object):
    def setupUi(self, CheatingListItem):
        CheatingListItem.setObjectName("CheatingListItem")
        CheatingListItem.setWindowModality(QtCore.Qt.NonModal)
        CheatingListItem.setEnabled(True)
        CheatingListItem.resize(196, 82)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CheatingListItem)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl1 = QtWidgets.QLabel(CheatingListItem)
        self.lbl1.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(8)
        self.lbl1.setFont(font)
        self.lbl1.setMouseTracking(True)
        self.lbl1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl1.setLineWidth(0)
        self.lbl1.setTextFormat(QtCore.Qt.RichText)
        self.lbl1.setOpenExternalLinks(False)
        self.lbl1.setObjectName("lbl1")
        self.verticalLayout.addWidget(self.lbl1)
        self.lbl2 = QtWidgets.QLabel(CheatingListItem)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(8)
        self.lbl2.setFont(font)
        self.lbl2.setMouseTracking(True)
        self.lbl2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl2.setLineWidth(0)
        self.lbl2.setTextFormat(QtCore.Qt.RichText)
        self.lbl2.setOpenExternalLinks(False)
        self.lbl2.setObjectName("lbl2")
        self.verticalLayout.addWidget(self.lbl2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(CheatingListItem)
        QtCore.QMetaObject.connectSlotsByName(CheatingListItem)
    def retranslateUi(self, CheatingListItem):
        _translate = QtCore.QCoreApplication.translate
        CheatingListItem.setWindowTitle(_translate("CheatingListItem", "cheating_list_item"))
        self.lbl1.setText(_translate("CheatingListItem", "lbl"))
        self.lbl2.setText(_translate("CheatingListItem", "lbl"))