from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_RealTimeCatch(object):
    def setupUi(self, RealTimeCatch):
        RealTimeCatch.setObjectName("RealTimeCatch")
        RealTimeCatch.resize(200, 208)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(7)
        RealTimeCatch.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resource/ico/scan.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RealTimeCatch.setWindowIcon(icon)
        RealTimeCatch.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(RealTimeCatch)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(RealTimeCatch)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.catch_img = QtWidgets.QLabel(RealTimeCatch)
        self.catch_img.setMinimumSize(QtCore.QSize(0, 135))
        self.catch_img.setMaximumSize(QtCore.QSize(10000, 150))
        self.catch_img.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.catch_img.setText("")
        self.catch_img.setObjectName("catch_img")
        self.verticalLayout.addWidget(self.catch_img)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(69, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.time_lbl = QtWidgets.QLabel(RealTimeCatch)
        self.time_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.time_lbl.setObjectName("time_lbl")
        self.horizontalLayout_2.addWidget(self.time_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(68, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.retranslateUi(RealTimeCatch)
        QtCore.QMetaObject.connectSlotsByName(RealTimeCatch)
    def retranslateUi(self, RealTimeCatch):
        _translate = QtCore.QCoreApplication.translate
        RealTimeCatch.setWindowTitle(_translate("RealTimeCatch", "real_time_catch"))
        self.label.setText(_translate("RealTimeCatch", "异常行为"))
        self.time_lbl.setText(_translate("RealTimeCatch", "00:00:00"))
